#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo "This script requires root privileges. Attempting to escalate..."
    sudo "$0" "$@"
    exit 0
fi

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
LOG_FILE="$SCRIPT_DIR/backup-check.log"
exec > >(tee -a "$LOG_FILE") 2>&1

restic check --read-data
