#!/bin/bash
# Requires installation of restic

if [ "$(id -u)" -ne 0 ]; then
    echo "This script requires root privileges. Attempting to escalate..."
    sudo "$0" "$@"
    exit 0
fi

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
source "$SCRIPT_DIR/.config"
LOG_FILE="$SCRIPT_DIR/backup.log"
exec > >(tee -a "$LOG_FILE") 2>&1

systemctl stop docker docker.socket

# Check hdd
echo "Checking local /storage mount..."
if ! mountpoint -q -- /storage; then
    echo "ERROR: /storage is not a valid mount point"
    exit 1
fi

BACKUP_NAME="backup-$(date +%F-%H-%M)"

echo "Creating system and homedir snapshot: $BACKUP_NAME"
zfs snapshot -r zroot@$BACKUP_NAME
zfs destroy zroot/swap@$BACKUP_NAME
zfs snapshot -r datapool@$BACKUP_NAME

echo "Creating backup: $BACKUP_NAME"
restic backup --verbose --skip-if-unchanged --compression max --tag $BACKUP_NAME $BACKUP_SOURCE
if [ $? -ne 0 ]; then
    echo "Backup failed at $(date)"
    exit 1
fi

echo "Pruning old backups"
restic forget --prune --keep-daily 7 --keep-weekly 4 --keep-monthly 12 --keep-within 1y
if [ $? -ne 0 ]; then
    echo "Prune failed at $(date)"
    exit 1
fi

echo "Backup completed successfully at $(date) - please reboot"
