#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo "This script requires root privileges. Attempting to escalate..."
    sudo "$0" "$@"
    exit 0
fi

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
source "$SCRIPT_DIR/.config"

echo "Pruning old backups"
restic forget --prune --keep-daily 7 --keep-weekly 4 --keep-monthly 12 --keep-within 1y
if [ $? -ne 0 ]; then
    echo "Prune failed at $(date)"
    exit 1
fi

echo "Pruned Restic"
